### ISSUE TITLE
certain area raises IndexError 

### ISSUE THREAD

**Issue by tailoric** [pietroalbini/reddit-place-2017#1]
using the script with the following parameters throws the following error 
`python35 generate.py data\diff.gz --area 312,371:443,534 --interval 3600 --output-dir mona_lisa/`

Edit: python version is 3.5.2

Output:  
```
Traceback (most recent call last):
  File "generate.py", line 260, in <module>
    main()
  File "generate.py", line 248, in main
    for timestamp in load_diff(args.diff, canvas):
  File "generate.py", line 146, in load_diff
    canvas.set(x, y, color)
  File "generate.py", line 86, in set
    self._pixels[x][y] = color
IndexError: list assignment index out of range
```

States of the variables at line 84 (before y gets its new value assigned):

![pycharm64_2017-04-04_15-40-07](https://cloud.githubusercontent.com/assets/16943959/24659459/049cd7e2-194d-11e7-8179-e94ac9ab4e54.png)

States of the variables at line 86 (when the error is raised):

![pycharm64_2017-04-04_15-41-58](https://cloud.githubusercontent.com/assets/16943959/24659543/439d81c6-194d-11e7-9bb3-9a07a2150c81.png)

**Comment by tailoric** [comment]
Finding the source of this error took me longer than it was necessary...

the bug is that in line 86:

```python
self._pixels[x][y] = color
```

is the wrong way around
it should be 
```python
self._pixels[y][x] = color
```
instead, with that fix it now works for me.

**Comment by emilyalbini** [comment]
Thank you for the bug report! I fixed the issue.
